# Basic
title: Wu Bigo
subtitle: Today I Learned
description: A collection of concise write-ups build from http://bigo.github.io .These are things that don't really warrant a full blog post
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Bigo
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Iaas / Paas /Big Data
url: "http://wubigo.com"

# Comment
comment:
    disqus: wubigo
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    github: wubigo
    # twitter:
    mail: wubigo@gmail.com



# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Archive, description: archive, url: '/archive'}
    - {title: Tags, description: tags, url: '/tags'}
    - {title: About, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
